/**
 * Generates the package's data from logos/:
 *   packages/core/src/generated/registry.ts   metadata for every valid entity (no image content)
 *   packages/core/src/generated/svg/<name>.ts SVG markup string, for SVG variants
 *   packages/core/assets/<name>.<svg|webp>     the shipped files
 *   packages/core/assets/native/<name>.png     PNG renderings of SVG logos, for React Native's <Image> (no SVG)
 * where <name> is the entity id for the logo and "<id>-mark" for the mark. The img/<name> modules that point at
 * these files are written after tsup by scripts/write-image-modules.ts.
 *
 * logos/ keeps rasters as lossless PNG (the originals); the package ships them as WebP, which is
 * about a third smaller at no visible cost at logo sizes. Encoded files are cached by content hash
 * in .cache/webp so rebuilds only encode new or changed logos.
 */
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';
import { formatOf, type LogoEntity, type LogoFormat } from '../packages/core/src/types.js';
import { readLogoFolders, ROOT } from './lib/logos.js';
import { validateFolders } from './lib/validate.js';

const CORE = join(ROOT, 'packages/core');
const OUT_DIR = join(CORE, 'src/generated');
const ASSET_DIR = join(CORE, 'assets');
const CACHE_DIR = join(ROOT, '.cache/webp');
const NATIVE_DIR = join(ASSET_DIR, 'native');
const NATIVE_CACHE_DIR = join(ROOT, '.cache/native-png');
/** Longest side of the PNG renderings of SVG logos (marks are square icons, so smaller). */
const NATIVE_SIDE = { logo: 512, mark: 256 } as const;
const HEADER = '// Generated by scripts/build-registry.ts. Do not edit.\n';
/** Shipped format for each source format. */
const SHIPPED: Record<LogoFormat, LogoFormat> = { svg: 'svg', png: 'webp', webp: 'webp' };

const folders = readLogoFolders();
const { entities, errors } = validateFolders(folders);
if (errors.length) {
  for (const e of errors) console.error(`error ${e}`);
  console.error('\nRegistry not built. Fix the errors above (npm run validate).');
  process.exit(1);
}

rmSync(OUT_DIR, { recursive: true, force: true });
rmSync(ASSET_DIR, { recursive: true, force: true });
for (const dir of [join(OUT_DIR, 'svg'), ASSET_DIR, NATIVE_DIR, CACHE_DIR, NATIVE_CACHE_DIR]) {
  mkdirSync(dir, { recursive: true });
}

async function toWebp(png: Buffer): Promise<{ bytes: Buffer; cached: boolean }> {
  const cacheFile = join(CACHE_DIR, `${createHash('sha256').update(png).digest('hex').slice(0, 32)}.webp`);
  if (existsSync(cacheFile)) return { bytes: readFileSync(cacheFile), cached: true };
  const bytes = await sharp(png).webp({ quality: 90, alphaQuality: 100, effort: 6 }).toBuffer();
  writeFileSync(cacheFile, bytes);
  return { bytes, cached: false };
}

/**
 * Renders an SVG to PNG for React Native. The root <svg> gets an explicit width/height from its viewBox first:
 * librsvg rejects some valid SVGs (e.g. a 0.43-unit-wide viewBox) when asked to scale by density.
 */
async function svgToPng(svg: string, side: number): Promise<{ bytes: Buffer; cached: boolean }> {
  const cacheFile = join(
    NATIVE_CACHE_DIR,
    `${createHash('sha256').update(`${side}:${svg}`).digest('hex').slice(0, 32)}.png`,
  );
  if (existsSync(cacheFile)) return { bytes: readFileSync(cacheFile), cached: true };
  const [, , w, h] = svg
    .match(/viewBox="([^"]+)"/)![1]!
    .trim()
    .split(/[\s,]+/)
    .map(Number) as number[];
  const scale = side / Math.max(w!, h!);
  const sized = svg
    .replace(/(<svg\b[^>]*?)\s(width|height)="[^"]*"/g, '$1')
    .replace(
      /<svg\b/,
      `<svg width="${Math.max(1, Math.round(w! * scale))}" height="${Math.max(1, Math.round(h! * scale))}"`,
    );
  const bytes = await sharp(Buffer.from(sized), { limitInputPixels: false })
    .png({ compressionLevel: 9, palette: true, quality: 90, effort: 10 })
    .toBuffer();
  writeFileSync(cacheFile, bytes);
  return { bytes, cached: false };
}

const text = (value: string) => `${HEADER}const value: string = ${JSON.stringify(value)};\nexport default value;\n`;
const folderById = new Map(folders.map((f) => [f.idDir, f]));
const counts = { svg: 0, webp: 0, encoded: 0, rendered: 0 };
const shipped: LogoEntity[] = [];

for (const entity of entities) {
  const folder = folderById.get(entity.id)!;
  const formats: NonNullable<LogoEntity['formats']> = {};
  for (const variant of entity.variants) {
    const source = formatOf(entity, variant);
    const format = SHIPPED[source];
    const src = join(folder.dir, `${variant}.${source}`);
    const name = variant === 'logo' ? entity.id : `${entity.id}-${variant}`;
    const file = `${name}.${format}`;
    if (format === 'svg') {
      copyFileSync(src, join(ASSET_DIR, file));
      const svg = readFileSync(src, 'utf8').trim();
      writeFileSync(join(OUT_DIR, 'svg', `${name}.ts`), text(svg));
      const { bytes, cached } = await svgToPng(svg, NATIVE_SIDE[variant]);
      writeFileSync(join(NATIVE_DIR, `${name}.png`), bytes);
      counts.svg++;
      if (!cached) counts.rendered++;
    } else {
      const { bytes, cached } = await toWebp(readFileSync(src));
      writeFileSync(join(ASSET_DIR, file), bytes);
      formats[variant] = format;
      counts.webp++;
      if (!cached) counts.encoded++;
    }
  }
  // The package reports the format it ships, not the source format in logos/.
  const { formats: _source, ...rest } = entity;
  shipped.push(Object.keys(formats).length ? { ...rest, formats } : rest);
}

const version: string = JSON.parse(readFileSync(join(CORE, 'package.json'), 'utf8')).version;
writeFileSync(
  join(OUT_DIR, 'version.ts'),
  `${HEADER}export const VERSION = ${JSON.stringify(version)};
`,
);

writeFileSync(
  join(OUT_DIR, 'registry.ts'),
  `${HEADER}import type { LogoEntity } from '../types.js';\n\nexport const registry: LogoEntity[] = ${JSON.stringify(shipped, null, 2)};\n`,
);

console.log(
  `registry: ${entities.length} entities, ${counts.svg} SVG (+ PNG renderings) + ${counts.webp} WebP files ` +
    `(${counts.encoded} newly encoded, ${counts.rendered} newly rendered) -> ${ASSET_DIR}`,
);
