/**
 * Generates packages/core/src/generated/:
 *   registry.ts        metadata for every valid entity (no SVG content)
 *   svg/<id>.ts        default export = the logo SVG string
 *   svg/<id>-mark.ts   default export = the icon-only mark, when the entity has one
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readLogoFolders, ROOT } from './lib/logos.js';
import { validateFolders } from './lib/validate.js';

const OUT_DIR = join(ROOT, 'packages/core/src/generated');
const SVG_DIR = join(OUT_DIR, 'svg');
const HEADER = '// Generated by scripts/build-registry.ts. Do not edit.\n';

const folders = readLogoFolders();
const { entities, errors } = validateFolders(folders);
if (errors.length) {
  for (const e of errors) console.error(`error ${e}`);
  console.error('\nRegistry not built. Fix the errors above (npm run validate).');
  process.exit(1);
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(SVG_DIR, { recursive: true });

writeFileSync(
  join(OUT_DIR, 'registry.ts'),
  `${HEADER}import type { LogoEntity } from '../types.js';\n\nexport const registry: LogoEntity[] = ${JSON.stringify(entities, null, 2)};\n`,
);

const folderById = new Map(folders.map((f) => [f.idDir, f]));
let files = 0;
for (const entity of entities) {
  const folder = folderById.get(entity.id)!;
  for (const variant of entity.variants) {
    const svg = readFileSync(join(folder.dir, `${variant}.svg`), 'utf8').trim();
    const name = variant === 'logo' ? entity.id : `${entity.id}-${variant}`;
    writeFileSync(
      join(SVG_DIR, `${name}.ts`),
      `${HEADER}const svg: string = ${JSON.stringify(svg)};\nexport default svg;\n`,
    );
    files++;
  }
}

console.log(`registry: ${entities.length} entities, ${files} SVG modules -> ${OUT_DIR}`);
