/**
 * Generates the package's data from logos/:
 *   packages/core/src/generated/registry.ts   metadata for every valid entity (no image content)
 *   packages/core/src/generated/svg/<name>.ts SVG markup string, for SVG variants
 *   packages/core/src/generated/img/<name>.ts data URI for <img src>, for every variant (SVG or PNG)
 *   packages/core/assets/<name>.<ext>          the raw files, for bundler URL imports and non-JS consumers
 * where <name> is the entity id for the logo and "<id>-mark" for the mark.
 */
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { formatOf } from '../packages/core/src/types.js';
import { readLogoFolders, ROOT } from './lib/logos.js';
import { validateFolders } from './lib/validate.js';

const CORE = join(ROOT, 'packages/core');
const OUT_DIR = join(CORE, 'src/generated');
const ASSET_DIR = join(CORE, 'assets');
const HEADER = '// Generated by scripts/build-registry.ts. Do not edit.\n';

const folders = readLogoFolders();
const { entities, errors } = validateFolders(folders);
if (errors.length) {
  for (const e of errors) console.error(`error ${e}`);
  console.error('\nRegistry not built. Fix the errors above (npm run validate).');
  process.exit(1);
}

rmSync(OUT_DIR, { recursive: true, force: true });
rmSync(ASSET_DIR, { recursive: true, force: true });
for (const dir of [join(OUT_DIR, 'svg'), join(OUT_DIR, 'img'), ASSET_DIR]) mkdirSync(dir, { recursive: true });

writeFileSync(
  join(OUT_DIR, 'registry.ts'),
  `${HEADER}import type { LogoEntity } from '../types.js';\n\nexport const registry: LogoEntity[] = ${JSON.stringify(entities, null, 2)};\n`,
);

const module = (value: string) => `${HEADER}const value: string = ${JSON.stringify(value)};\nexport default value;\n`;
const folderById = new Map(folders.map((f) => [f.idDir, f]));
const counts = { svg: 0, png: 0 };

for (const entity of entities) {
  const folder = folderById.get(entity.id)!;
  for (const variant of entity.variants) {
    const format = formatOf(entity, variant);
    const file = join(folder.dir, `${variant}.${format}`);
    const name = variant === 'logo' ? entity.id : `${entity.id}-${variant}`;
    copyFileSync(file, join(ASSET_DIR, `${name}.${format}`));
    if (format === 'svg') {
      const svg = readFileSync(file, 'utf8').trim();
      writeFileSync(join(OUT_DIR, 'svg', `${name}.ts`), module(svg));
      writeFileSync(
        join(OUT_DIR, 'img', `${name}.ts`),
        module(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`),
      );
    } else {
      const png = readFileSync(file).toString('base64');
      writeFileSync(join(OUT_DIR, 'img', `${name}.ts`), module(`data:image/png;base64,${png}`));
    }
    counts[format]++;
  }
}

console.log(`registry: ${entities.length} entities, ${counts.svg} SVG + ${counts.png} PNG files -> ${OUT_DIR}`);
